# Runs all the Python SDK tests within the `tests/` directory to check our code

name: CI Tests
permissions: read-all

on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # github.workflow: name of the workflow
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

jobs:
  pytest:
    name: pytest (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: cnine
          environment-file: environment.yml
      - name: Install Missing Developper packages
        run: conda install pytest
      - name: Setting environment variables
        run: echo "$CONDA_PREFIX" >> $CUDA_HOME
      - name: Install and build
        run: pip install python/
      - name: Test with pytest
        run: pytest python/tests
